#!/bin/bash

source .config

for DIR in "${DIRS[@]}"; do
    echo "Updating: $DIR..."
    cd "$DIR"
    rm -fr "$PHIRE"
    wget http://updates.phirecms.org/releases/phire/phirecms.zip
    unzip phirecms.zip
    rm phirecms.zip
    cd "$PHIRE_CONTENT/assets"
    rm -fr ./*
    cp ../index.html .

    if [ "$1" = "-m" ]; then
        echo "Updating Modules..."
        cd ../modules
        MODULES=$(ls)
        rm -fr ./phire-*
        for M in $MODULES; do
            if [[ $M == *".zip"* ]]; then
                wget "http://updates.phirecms.org/releases/modules/$M"
                unzip "$M"
            fi
        done
    fi

    cd "$DIR"
    chown -R "$OWNER" ./*
    chmod -R 777 "$PHIRE_CONTENT"
done

echo "Complete!"
